name: Deployment_base_href
on:
  push:
    branches: [master, opruiming]
jobs:
  Change_base_href:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install --only=prod
      - name: Update base href
        run: node scripts/dep.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: "Dylan Sealy"
          author_email: 66305635+DylanSealy@users.noreply.github.com
          message: "GitHub action: deployment base href"
          push: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
